# Identity without an account.
#
# Doc 2 §2.9 rule 8: value before permission, permission before account. So the
# fridge is identified by an opaque token the browser holds in two independent
# places — localStorage (survives cookie clearing) and a ten-year cookie
# (survives a cleared localStorage). Either one alone restores the fridge.
#
# The trade is explicit: lose both and the fridge is gone. That is acceptable for
# a product whose entire inventory is regenerated by one photo of the next shop.
module FridgeIdentifiable
  extend ActiveSupport::Concern

  COOKIE_NAME = :scrapless_fridge

  included do
    attr_reader :current_household
  end

  private

  def authenticate!
    token = bearer_token.presence || cookies.signed[COOKIE_NAME].presence
    return render_unauthorized unless token

    @current_household = Household.find_by(token: token)
    return render_unauthorized unless @current_household

    refresh_cookie(@current_household)
    @current_household.touch_seen!
  end

  def bearer_token
    request.headers["Authorization"].to_s.split("Bearer ").last
  end

  # Re-stamped on every request, so an active fridge is never ten years from
  # expiry — it is always ten years from its last visit.
  def refresh_cookie(household)
    cookies.signed[COOKIE_NAME] = {
      value: household.token,
      expires: Household::TOKEN_LIFETIME.from_now,
      httponly: true,
      same_site: :lax,
      secure: request.ssl?
    }
  end

  def clear_cookie
    cookies.delete(COOKIE_NAME)
  end

  def render_unauthorized
    render json: { error: I18n.t("auth.no_fridge") }, status: :unauthorized
  end
end
